Repository kopiLeft/Galite, pull requests merged in 2020-12, with the labels that each got.

#145 Improvement of classes/methods documentation comments
  galite-core/src/main/kotlin/org/kopi/galite/common/Actor.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Menu.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Trigger.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FieldAlignment.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormPage.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
Labels: documentation

#147 adding block options
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/BlockOption.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormTests.kt
Labels: enhancement, form DSL

#151 Implementing block buildQueryDialog()
  galite-core/src/main/kotlin/org/kopi/galite/form/AbstractPredefinedValueHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/PredefinedValueHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VWeekField.kt
Labels: database

#148 Report triggers
  galite-core/src/main/kotlin/org/kopi/galite/common/Action.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/BlockAction.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Trigger.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Window.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/ReportSelectionForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: enhancement, report DSL

#118 add fetchlookup method
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/VBaseRowTests.kt
Labels: database, enhancement

#157 Adding a method to run specific form
  galite-core/src/main/kotlin/org/kopi/galite/db/Connection.kt
  galite-core/src/main/kotlin/org/kopi/galite/db/DBSchema.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VDatabaseUtils.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
  galite-core/src/main/kotlin/org/kopi/vkopi/lib/ui/swing/visual/DMenuTree.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/db/DBSchemaTest.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/desktop/Application.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSampleTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFields.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFieldsTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/util/ReflectToolTests.kt
Labels: test

#144 Form field options
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FieldOption.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
Labels: enhancement, form DSL

#163 Refactoring demo Application methods to DBSchemaTest
  galite-tests/src/main/kotlin/org/kopi/galite/tests/db/DBSchemaTest.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/desktop/Application.kt
Labels: test

#119 Adding Fetch , search and join Conditions feature in exposed
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlockDefaultOuterJoin.kt
Labels: database, enhancement

#158 Readme update
  README.md
Labels: documentation

#127 Add trigger feature in DSL
  galite-core/src/main/kotlin/org/kopi/galite/common/Trigger.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/util/ReflectToolTests.kt
Labels: enhancement, form DSL

#169 recursiveQuery command in a block with one table
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlockDefaultOuterJoin.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/list/VColumn.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFields.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockDefaultOuterJoinTests.kt
Labels: database, enhancement, form DSL, model

#172 Adding saveBlock command
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/DictionaryForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlockIndex.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
Labels: enhancement, form DSL

#176 Supporting nullable fields
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/Dimension.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/DimensionData.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/Measure.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/CodeDomain.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/ListDomain.kt
  galite-core/src/main/kotlin/org/kopi/galite/exceptions/InvalidValueException.kt
  galite-core/src/main/kotlin/org/kopi/galite/exceptions/MissingMeasureException.kt
  galite-core/src/main/kotlin/org/kopi/galite/field/Field.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlockDefaultOuterJoin.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormDescriptionPosition.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormFieldColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormFieldColumns.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportRow.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFields.kt
Labels: enhancement

#161 adding serialVersionUID to serializable classes
  galite-core/src/main/kotlin/org/kopi/galite/base/ExtendedChoiceFormat.kt
  galite-core/src/main/kotlin/org/kopi/galite/base/ExtendedMessageFormat.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFieldException.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VQueryNoRowException.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VQueryOverflowException.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VSkipRecordException.kt
  galite-core/src/main/kotlin/org/kopi/galite/print/PSPrintException.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ColumnStyle.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/MReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VBaseRow.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VGroupRow.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VNoRowException.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReportRow.kt
  galite-core/src/main/kotlin/org/kopi/galite/util/FaxException.kt
  galite-core/src/main/kotlin/org/kopi/galite/util/PrintException.kt
  galite-core/src/main/kotlin/org/kopi/galite/util/base/InconsistencyException.kt
  galite-core/src/main/kotlin/org/kopi/galite/util/base/NotImplementedException.kt
  galite-core/src/main/kotlin/org/kopi/galite/util/lpr/LpdException.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/PropertyException.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VException.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VExecFailedException.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VInterruptException.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VRuntimeException.kt
Labels: model

#180 adding minValue & maxValue for Int Field
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
Labels: enhancement, form DSL

#174 Generating VDefaultActor models
  galite-core/src/main/kotlin/org/kopi/galite/common/Actor.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/VKConstants.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
Labels: form DSL, model

#182 Github Action: Setup CI workflow
  .github/workflows/gradle.yml
  README.md
Labels: enhancement

#185 Form with multiple block fixes
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithMultipleBlockTests.kt
Labels: bug, form DSL

#177 Adding VBlockDefaultOuterJoin tests
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlockDefaultOuterJoin.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/JApplicationTestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockDefaultOuterJoinTests.kt
Labels: test

#187 Implementing VBlock.isNullReference
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
Labels: database, enhancement

#94 login page
  .gitignore
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/LocalizedProperties.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/ResourcesUtil.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Styles.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/StylesInjector.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VAnchorPanel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VHiddenSeparator.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VInputButton.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VInputLabel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VInputText.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VScrollablePanel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VSingleRowTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VCompanyLogo.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VContent.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VHeader.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VLogo.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VMain.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VSelect.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VSimpleTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/Window.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/event/DropActionListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/event/FieldListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/event/LoginWindowListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/event/MainWindowListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/event/PositionPanelListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VEmptyModuleList.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginBox.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginView.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/VReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/VTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplicationContext.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VFileHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VImageHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VPreviewRunner.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VUIFactory.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/welcome/WelcomeView.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/welcome/WelcomeViewEvent.kt
  galite-tests/build.gradle.kts
  galite-tests/src/main/kotlin/org/kopi/galite/tests/VApplicationTestBase.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/base/UITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/AppShell.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/Application.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/report/VReportTests.kt
Labels: UI, enhancement

#189 Adding new lookupColumn implementation, deprecating the old one
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
Labels: enhancement

#164 Add checkRecordUnchanged method in VBlock
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
Labels: database

#160 Implementing methods: save() and load()
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
Labels: database

#162 adding VBlock.getSearchOrder() method
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: database

#193 Notification component
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VSpan.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/ConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/ErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/NotificationListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VAbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VErrorMessagePopup.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VInformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VWarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/WarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/AppShell.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/Application.kt
Labels: UI, enhancement

#194 Image model UI implementation
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Image.kt
Labels: UI, enhancement, model

#168 Implementation of deleteRecord in VBlock
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VDatabaseUtils.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: database

#166 adding VBlock.checkUniqueIndex() method
  galite-core/src/main/kotlin/org/kopi/galite/db/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VIntegerCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VIntegerField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: database

#196 Report model UI implementation
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/VReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/VTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/report/VReportTests.kt
Labels: UI, enhancement, model

#153 adding selectLookup method under VBlock
  galite-core/src/main/kotlin/org/kopi/galite/db/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VTimestampField.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Timestamp.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: database

#178 adding Commands to Form
  galite-core/src/main/kotlin/org/kopi/galite/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
Labels: form DSL

#195 Chart model UI implementation
  galite-core/src/main/kotlin/org/kopi/galite/chart/VChartType.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VMeasureData.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DAbstractChartType.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DAreaChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DBarChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DColumnChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DLineChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/DPieChart.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/chart/VChartTypeFactory.kt
Labels: UI, enhancement, model

#152 Implementation of getSearchConditions()
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VStringCodeField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/util/ReflectToolTests.kt
Labels: database
