Repository kopiLeft/Galite, pull requests merged in 2021-09, with the labels that each got.

#417 UI/JS: Fix copy-paste issue for text editor
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/RichTextField.kt
  galite-core/src/main/resources/META-INF/resources/frontend/src/wysiwyg-e-rich-text.js
Labels: UI, UI: form, frontend

#425 VaadinUI: Enable to initialize mandatory boolean field from server side
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/BooleanField.kt
Labels: UI :computer:, UI: form

#418 Support subqueries in an insert statement
  galite-core/src/main/kotlin/org/kopi/galite/db/Expressions.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
Labels: enhancement, database :floppy_disk:

#420 VaadinUI: Implementing the preview window for displaying external documents
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/preview/DPreviewWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/preview/EmbeddedDocument.kt
Labels: UI :computer:

#426 Release lock on upload when on dialog close
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
Labels: UI :computer:

#423 VaadinUI: Implement shortcuts for RichText field
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/RichTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DRichTextEditor.kt
Labels: UI 💎, UI: form

#422 UI/JS: Enable focus on a richtext field
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/RichTextField.kt
  galite-core/src/main/resources/META-INF/resources/frontend/src/wysiwyg-e-rich-text.js
Labels: enhancement, frontend

#429 VaadinUI: Discover manually AppShellConfigurator for springboot based applications
  README.md
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-tests/src/main/kotlin/org/kopi/galite/demo/vaadin/Application.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VApplicationTestBase.kt
  galite-tests/src/main/resources/META-INF/resources/favicon.png
  galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestApplication.kt
Labels: UI 💎

#430 VaadinUI: close all opened dialogs on logout
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
Labels: bug :lady_beetle:, UI 💎

#437 Adding VDialog Component
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VDialog.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/dialog.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/list.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/notification.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/windows.css
Labels: enhancement, UI 💎

#428 VaadinUI: Add stacktrace to fatal error notification
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/LocalizedProperties.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorNotification.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/notification.css
Labels: enhancement, UI 💎

#442 Vbump: Vaadin 21
  .gitignore
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
  galite-core/build.gradle.kts
  galite-tests/build.gradle.kts
Labels: v bump🔺

#443 Vbump: Karibu-Testing 1.3.3
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
  galite-testing/src/main/kotlin/org/kopi/galite/testing/Block.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
Labels: v bump🔺

#441 VBump: EnhancedDialog 21.0.0
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
Labels: v bump🔺

#440 Vbump: Kotlin 1.5.30
  build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/common/TestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomainsTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithSpecialTypes.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: v bump🔺

#431 Test exposed methods of VBlock & VField
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/Database.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
Labels: test :test_tube:

#421 VaadinUI: Set UI when thread is started before component get attached
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/form.css
Labels: enhancement, UI 💎

#448 Create index.html the entry point of user guide, javadoc, code & issu…
  css/index.css
  docs/logo_galite.png
  index.html
  javadoc.html
Labels: documentation :page_facing_up:

#447 Vbump: Exposed 0.35.1
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
Labels: v bump🔺

#438 Display wait dialog while executing a transaction
  galite-core/src/main/kotlin/org/kopi/galite/cross/VDynamicReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/db/WindowTransaction.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/Commands.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: enhancement, model, UI 💎, database :floppy_disk:

#435 VaadinUI: Reset selection when focus on richtext field
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/RichTextField.kt
  galite-core/src/main/resources/META-INF/resources/frontend/src/wysiwyg-e-rich-text.js
Labels: enhancement, UI 💎, frontend

#419 Enhancements: sql logging level and improve UI components
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/visual/JApplication.java
  galite-core/src/main/kotlin/org/kopi/galite/db/Connection.kt
  galite-core/src/main/kotlin/org/kopi/galite/db/DBContext.kt
  galite-core/src/main/kotlin/org/kopi/galite/db/DBSchema.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Tree.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/richtext.css
  galite-tests/build.gradle.kts
  galite-tests/src/main/kotlin/org/kopi/galite/tests/db/DBSchemaTest.kt
  galite-tests/src/main/resources/simplelogger.properties
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/list/ListTests.kt
Labels: enhancement, UI 💎, database :floppy_disk:, waiting upstream

#451 Ext: Adding text field type
  galite-core/src/main/kotlin/org/kopi/galite/visual/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/domain/GaliteDomains.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VTextField.kt
Labels: model, domain

#445 Database: Handle transaction failure - abort trail
  galite-core/src/main/kotlin/org/kopi/galite/visual/cross/VDynamicReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/Commands.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/visual/VExecFailedException.kt
Labels: database :floppy_disk:

#455 Tests: Adding Form DSL tests
  README.md
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/dsl/FormPage.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/dsl/FormDSLTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/FormExample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/FormWithChart.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/ManyPagesForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSampleTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithAlignedBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithChart.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/util/ReflectToolTests.kt
Labels: test :test_tube:

#456 VaadinUI: Supporting image fields
  galite-core/src/main/kotlin/org/kopi/galite/visual/db/Types.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/db/WindowTransaction.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VBooleanCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VColorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VDateField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VFixnumCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VFixnumField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VIntegerCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VIntegerField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VMonthField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VStringCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VStringField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VTimeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VTimestampField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/VWeekField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/report/VBooleanCodeColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/type/Month.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/type/Time.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/type/Timestamp.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/field/ImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/form/DBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/form/DGridEditorBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/form/DImageField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithSpecialTypes.kt
Labels: model, UI 💎, database :floppy_disk:, UI: form
