Repository kopiLeft/Galite, pull requests merged in 2021-01, with the labels that each got.

#203 CHARTTYPE trigger
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Trigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
Labels: bug, chart DSL, enhancement

#201 Supporting menu, actors and commands in charts and reports
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartLocalizationWriter.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Actor.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Command.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Window.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormLocalizationWriter.kt
  galite-core/src/main/kotlin/org/kopi/galite/l10n/ActorLocalizer.kt
  galite-core/src/main/kotlin/org/kopi/galite/l10n/MenuLocalizer.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportLocalizationWriter.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithChart.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: chart DSL, enhancement, report DSL

#206 fix under report when adding data to fields
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: bug, report DSL

#207 Report field without label
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportLocalizationWriter.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/CodeDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/ListDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/VReportTests.kt
Labels: enhancement, report DSL

#208 Compute and format triggers in report field
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Triggers.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VCCDepthFirstCircuitN.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/CodeDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/ListDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/VReportTests.kt
Labels: enhancement, report DSL

#210 adding triggers for fields
  galite-core/src/main/kotlin/org/kopi/galite/field/FieldTriggers.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
Labels: enhancement, form DSL

#213 Export report to file commands
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: enhancement, report DSL

#217 Fix bug when saving report under xls & xlsx format
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/report/MReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/PExport.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/PExport2Excel.kt
Labels: enhancement

#170 adding insertRecord & updateRecord methods in VBlock
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
Labels: database

#211 Color and Format triggers in chart
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartDimension.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VColumnFormat.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
Labels: chart DSL, enhancement

#220 adding displayQueryList_ method under VField
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
Labels: database

#219 adding VField.getListId() method
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
Labels: database

#214 Implementation + test of Vfield.checkList method
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/list/VList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
Labels: database

#223 Add VWindows component
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindows.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/Application.kt
Labels: UI

#192 Add selectFromList() in VField
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
Labels: database

#226 Implementation of VField.setValueID()
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomains.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomainsTests.kt
Labels: database

#230 List Domain displaying list data in a dialog
  galite-core/src/main/kotlin/org/kopi/galite/common/ListDescription.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/ListDomain.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/UListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/desktop/Application.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/ListDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomains.kt
Labels: bug, database, domain, enhancement

#232 Changing CodeDomain.set() to keyOf()
  galite-core/src/main/kotlin/org/kopi/galite/domain/CodeDomain.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/CodeDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithCodeDomains.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/report/VReportTests.kt
Labels: domain, enhancement

#191 The "Decimal" type
  galite-core/src/main/kotlin/org/kopi/galite/base/ExtendedChoiceFormat.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartDimension.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VFixnumCodeDimension.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VFixnumCodeMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VFixnumDimension.kt
  galite-core/src/main/kotlin/org/kopi/galite/chart/VFixnumMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/cross/VDynamicReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/db/Query.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormFieldColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/list/VFixnumCodeColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/list/VFixnumColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/MReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/PExport2Excel.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Triggers.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VFixnumCodeColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VFixnumColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Decimal.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Fixed.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullFixed.kt
  galite-core/src/main/resources/org/kopi/galite/VlibProperties-ar_TN.xml
  galite-core/src/main/resources/org/kopi/galite/VlibProperties-de_AT.xml
  galite-core/src/main/resources/org/kopi/galite/VlibProperties-en_GB.xml
  galite-core/src/main/resources/org/kopi/galite/VlibProperties-fr_FR.xml
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithSpecialTypes.kt
Labels: domain

#233 Decimal type for charts and reports
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Triggers.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: domain, enhancement

#155 Add Image Type for fields
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Image.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithSpecialTypes.kt
Labels: domain, enhancement

#234 Enhancement of types usage
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/form/DateChooser.java
  galite-core/src/main/kotlin/org/kopi/galite/db/Query.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VDateField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VMonthField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VTimeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VWeekField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Triggers.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Date.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Decimal.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Month.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullDate.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullMonth.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullTime.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullTimestamp.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/NotNullWeek.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Time.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Timestamp.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Type.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Week.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: domain, enhancement

#186 adding method that Change the visibility of the block
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Access.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Modes.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSampleTests.kt
Labels: form DSL

#237 Display modules list menu after login
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VAnchorPanel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VCompanyLogo.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VHeader.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWelcome.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindows.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/ModuleItem.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/ModuleList.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/ModuleListMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DBookmarkMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/welcome/WelcomeView.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationConfiguration.kt
  galite-tests/src/test/resources/org/kopi/galite/test/Menu-fr_FR.xml
Labels: UI, enhancement

#241 Adding automatic push mode and attaching window from background thread
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
Labels: UI, enhancement

#244 Implementation of VField.getSearchCondition()
  galite-core/src/main/kotlin/org/kopi/galite/db/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/Commands.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBooleanCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VColorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VDateField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VIntegerCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VIntegerField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VMonthField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VStringCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VTimeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VTimestampField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VWeekField.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Date.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Decimal.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Image.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Month.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Time.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Timestamp.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Type.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Week.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: bug, database, enhancement

#242 Implementing form pages
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/form/VForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/Page.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
Labels: UI, enhancement

#247 Enhancement of triggers
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Trigger.kt
  galite-core/src/main/kotlin/org/kopi/galite/field/FieldTriggers.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VConstants.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Access.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFields.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: enhancement

#243 Implement StoreApplication
  galite-tests/src/test/kotlin/org/kopi/galite/demo/StoreApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/bill/BillForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/billproduct/BillProductForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/billproduct/BillProductR.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientR.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/command/CommandForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductR.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/stock/StockForm.kt
Labels: test
