Repository kopiLeft/Galite, pull requests merged in 2021-02, with the labels that each got.

#254 Introduce withReport and withChart helper methods for unit tests
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/chart/DChart.java
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/report/DReport.java
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/JApplicationTestBase.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/TestBase.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/VApplicationTestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/VReportTests.kt
Labels: enhancement, test

#252 Enhancement of Domains and adding months and times
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/common/CodeDescription.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/FieldList.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/ListDomain.kt
  galite-core/src/main/kotlin/org/kopi/galite/field/Field.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormFieldColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormFieldColumns.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/MustFillFormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/NullableFormField.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Date.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Decimal.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Image.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Month.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Time.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Timestamp.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Type.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Type0.kt
  galite-core/src/main/kotlin/org/kopi/galite/type/Week.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/CodeDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/domain/ListDomainTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSampleTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormToCheckFieldVisibility.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithBlockTrigger.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithFields.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithSpecialTypes.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: domain, enhancement

#246 Implementation of VActorPanel
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/KeyCode.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/actor/Actor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindowContainer.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DActor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/window/VActorPanel.kt
  galite-core/src/main/resources/META-INF/resources/frontend/images/bread_crumb_separator.png
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/vActorPanelStyles.css
Labels: UI

#149 add field droppable feature
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/util/ReflectToolTests.kt
Labels: enhancement, form DSL

#258 Support joins for tables defined in a form based on declared columns
  galite-core/src/main/kotlin/org/kopi/galite/form/Commands.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlockDefaultOuterJoin.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockDefaultOuterJoinTests.kt
Labels: database

#257 Handle updating cached records of form fields
  galite-core/src/main/kotlin/org/kopi/galite/form/UField.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VFieldUI.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/AbstractBlockLayout.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/Block.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/CachedValue.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/ColumnView.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/MultiBlockLayout.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/SimpleBlockLayout.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/AbstractField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/Field.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextValidator.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DLabel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DActor.kt
Labels: UI

#260 Type compatibility between report fields and table columns
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportField.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/ReportRow.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VFixnumColumn.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/StoreApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductR.kt
Labels: domain, report DSL

#259 Perform command action on click on actor
  galite-core/src/main/kotlin/org/kopi/galite/form/UForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/actor/Actor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DActor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
Labels: UI

#263 Report localization enhancement
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/DictionaryForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/ReportSelectionForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/VReportColumn.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VHelpViewer.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
Labels: localization

#262 UI: Report data table implementation
  galite-core/src/main/kotlin/org/kopi/galite/report/MReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/VTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientR.kt
Labels: UI: report

#215 Implement Notification UI Components
  build.gradle.kts
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/chart/ChartMeasure.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/CheckTypeException.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/NotificationListener.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/NotificationUtils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VAbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorMessagePopup.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VInformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VWarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/WarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VAbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/VErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notification/WarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-tests/build.gradle.kts
Labels: UI, enhancement

#264 Code Refactor: change in packages
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/form/DTextField.java
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/visual/DWindow.java
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/visual/JUIFactory.java
  galite-core/src/main/java/org/kopi/vkopi/lib/ui/swing/visual/MenuItemRenderer.java
  galite-core/src/main/kotlin/org/kopi/galite/ui/swing/visual/DMenuTree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/swing/visual/MenuItemRenderer.kt
Labels: enhancement

#265 Web-UI: Generate report to file
  galite-core/src/main/kotlin/org/kopi/galite/report/UReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/FileUploader.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VFileHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/Application.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/FileHandler.kt
Labels: UI, UI: report

#269 Update dependencies versions
  build.gradle.kts
  galite-core/build.gradle.kts
Labels: version-bump

#273 Support java 8
  .github/workflows/gradle.yml
  galite-core/src/main/kotlin/org/kopi/galite/chart/Chart.kt
  galite-core/src/main/kotlin/org/kopi/galite/common/Window.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormElement.kt
  galite-core/src/main/kotlin/org/kopi/galite/report/Report.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/base/UITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/report/ReportTests.kt
Labels: enhancement

#261 Adding nullable feature for columns
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumnTest.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumns.kt
Labels: form DSL

#266 Implementation of DateField
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextValidator.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/VDateField.kt
Labels: UI

#270 Handling application errors with showing notification dialog
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/BackgroundThreadHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/Field.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/NotificationUtils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VAbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VInformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VWarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/WarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DActor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/Action.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/command/CommandForm.kt
Labels: UI
