Repository kopiLeft/Galite, pull requests merged in 2021-07, with the labels that each got.

#357 VaadinUI: make the list dialog width responsive
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Styles.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/list/GridListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/list/ListTable.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/list.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/report.css
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/Application.kt
Labels: UI, UI: form

#337 Vaadin UI: Preserve page on refresh
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/BackgroundThreadHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Tree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/AlignPanel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/ImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextFieldNavigationHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DBlockDropHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DForm.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorLabel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridTextEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DLabel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/Page.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/VPredefinedValueHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DActor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DItemTree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/Tree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplicationContext.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/ChartSample.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithChart.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithCodeDomains.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomains.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumns.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockDefaultOuterJoinTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: UI

#361 VaadinUI: report style enhancement
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/ColumnStyleGenerator.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/ReportCellStyler.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/grid.css
Labels: UI, UI: report, enhancement

#360 VaadinUI: read field value when performing action of navigation shortcut
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/ShortcutAction.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/Field.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/InputTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/KeyNavigator.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/ObjectField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextFieldNavigationHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DObjectField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DRichTextEditor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorEnumField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorFixnumField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorTimeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorWeekField.kt
Labels: UI, UI: form

#366 VaadinUI: allow the browser's feature to save the entered credentials
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VInputPasword.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginBox.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
Labels: UI

#364 VaadinUI: exclusive access to components from background thread
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/InputTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DChartBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridMultiBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridTextEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DLabel.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DMultiBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
Labels: UI

#293 Implementation of RichTextField
  buildSrc/src/main/kotlin/org/kopi/galite/gradle/Versions.kt
  galite-core/build.gradle.kts
  galite-core/src/main/kotlin/org/kopi/galite/db/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/domain/Domain.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/RichTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DRichTextEditor.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/GShopApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/taxRule/TaxRuleForm.kt
Labels: UI: form

#365 VaadinUI: implementation of VApplication.userIP
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
Labels: UI

#321 Implementation of showHideFilter command
  galite-core/src/main/kotlin/org/kopi/galite/form/Commands.kt
  galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlockFilter.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/block.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/grid.css
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
Labels: UI, UI: form

#368 VaadinUI: reset original window title on logout
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/AppShell.kt
Labels: UI

#367 VaadinUI: Fix feature of switch window and improve WindowMenu style
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/Form.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindowContainer.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindowsMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/WarningNotification.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/header.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/list.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/windows.css
  galite-tests/src/test/kotlin/org/kopi/galite/demo/bill/BillForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/billproduct/BillProductForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/command/CommandForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/provider/ProviderForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/stock/StockForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/taxRule/TaxRuleForm.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
Labels: UI, enhancement

#371 Improvement of CSS Style
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/Page.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/block.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/form.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/list.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/notification.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/styles.css
Labels: UI, enhancement, frontend

#369 VaadinUI: show exception details for fatal errors
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/Block.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/CheckTypeException.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/InvalidEditorFieldException.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/NotificationUtils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
  galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/swing/JApplicationTestBase.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VApplicationTestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/Application.kt
Labels: UI

#373 VaadinUI: create window components via UI.access
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/ImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
  galite-tests/build.gradle.kts
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/FormTests.kt
Labels: UI

#378 Unit test: assert that the field value is sent to the model
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/block/SimpleBlockTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/FormTests.kt
Labels: test

#370 VaadinUI: Execute login asynchronously
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/VInputPasword.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginBox.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/login/VLoginWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/welcome/WelcomeView.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/login.css
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/login/LoginPageTests.kt
Labels: UI

#379 Improvement of Notification & PopUp Window Style
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/common/VHeader.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/ModuleList.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/ModuleListMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DMainMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/window/PopupWindow.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/header.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/styles.css
Labels: enhancement, frontend

#374 VaadinUI: implement editor fields with AbstractField
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridTextEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorActorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorImageField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorTextField.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/block.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/checkbox.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/header.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/styles.css
Labels: UI, UI: form

#380 Fix IllegalArgumentException when sorting application modules
  galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
Labels: model

#375 VaadinUI: Display localized representation for boolean fields
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorBooleanField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridEditorField.kt
Labels: UI, UI: form

#384 BugFix: Fix NPE when selecting value from dialog
  galite-core/src/main/kotlin/org/kopi/galite/form/UListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
Labels: UI, enhancement

#372 Improvement of TextField width
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/VCodeField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/VTextAreaField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/list/GridListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/window/PopupWindow.kt
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/block.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/checkbox.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/combobox.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/list.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/richtext.css
  galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/styles.css
Labels: UI, UI: form, enhancement

#376 VaadinUI: Bugfix in grid block and MainWindow
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/ShortcutAction.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/Block.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/CheckTypeException.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/InputTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/TextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/VDateField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/VTimeStampField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DGridBlock.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/InvalidEditorFieldException.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/VActorsRootNavigationItem.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/menu/VNavigationMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ConfirmNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/InformationNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/NotificationUtils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/WarningNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DItemTree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/window/PopupWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/window/Window.kt
Labels: UI, UI: form, enhancement

#377 VaadinUI: change PushMode to MANUAL
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/BackgroundThreadHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/Utils.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/form/DListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/list/GridListDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/FileUploader.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/upload/UploadDialog.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DItemTree.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DMenu.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/login/LoginPageTests.kt
Labels: UI, enhancement

#386 VaadinUI: show error notification when generating a report without data
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/BackgroundThreadHandler.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/grid/GridEditorTextField.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/AbstractNotification.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VWindowController.kt
Labels: UI, enhancement

#389 VaadinUI: Adding tests for Galite reports
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DReport.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/DTable.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/report/ReportCellStyler.kt
  galite-testing/src/main/kotlin/org/kopi/galite/testing/Actor.kt
  galite-testing/src/main/kotlin/org/kopi/galite/testing/MainWindow.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/common/TestBase.kt
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/GShopApplication.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/desktop/Application.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithReport.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/module/Modules.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/block/SimpleBlockTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/FormTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/login/LoginPageTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/main/MainWindowTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/VReportTests.kt
  galite-tests/src/test/resources/org/kopi/galite/demo/Menu-en_GB.xml
  galite-tests/src/test/resources/org/kopi/galite/test/Menu-en_GB.xml
Labels: UI: report, test

#392 Fix selectLookupTest under VBlockTests
  galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VBlockTests.kt
Labels: database, test

#390 VaadinUI: Adding tests for "List" command
  galite-tests/build.gradle.kts
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VUITestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithList.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithListDomains.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/module/Modules.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/list/ListTests.kt
  galite-tests/src/test/resources/org/kopi/galite/test/Menu-en_GB.xml
Labels: test

#387 VaadinUI: Set page title and icon
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/VWindowContainer.kt
  galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
  galite-core/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  galite-tests/src/main/kotlin/org/kopi/galite/tests/ui/vaadin/VApplicationTestBase.kt
  galite-tests/src/test/kotlin/org/kopi/galite/demo/web/vaadin/Application.kt
  galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/application/ConfigurationTests.kt
Labels: UI
